version: '3.4'
services:
  db:
    image: irlan/mysql-simian
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: dna
    ports:
      - "3308:3308"
    networks:
      - meli-network
  simian-app:
    image: irlan/app-simian
    restart: always
    build: ./simian
    working_dir: /simian
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes: 
      - ./simian:/simian
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - meli-network
networks:
    meli-network:
        driver: bridge
